### ISSUE TITLE
Implement validation for user  information struct

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/raccoon#149]
The user information struct defined [here](https://github.com/opeolluwa/racoon/blob/master/src/models/users.rs#L64), has many Optional fields (defined with `Option<T>`) and a few fixed ones,  

1. Implement validation for all the fixed and Optional fields using the [validator crate](https://crates.io/crates/validator) which is already added to the project. 

2. Write unit test at the base of the [module](https://github.com/opeolluwa/racoon/blob/master/src/models/users.rs)

**Comment by redredacted** [comment]
May I try to implement this?

**Comment by opeolluwa** [comment]
Yes, please. 
Thanks for reaching out to contribute

**Comment by opeolluwa** [comment]
@redredacted 
How is it going 😄

**Comment by opeolluwa** [comment]
fixed!
