### ISSUE TITLE
Add a roadmap where contributors do find things to help on

### ISSUE THREAD

**Issue by janpauldahlke** [opeolluwa/raccoon#151]
i've read it in the 'this week in rust' newsletter.
title is program, close it after please. kind regards
<img width="738" alt="Screenshot 2023-03-24 at 14 44 43" src="https://user-images.githubusercontent.com/19912915/227537944-27bdcb52-8b95-4cb8-99ba-f0d22f669e86.png">

**Comment by opeolluwa** [comment]
> i've read it in the 'this week in rust' newsletter. title is program, close it after please. kind regards <img alt="Screenshot 2023-03-24 at 14 44 43" width="738" src="https://user-images.githubusercontent.com/19912915/227537944-27bdcb52-8b95-4cb8-99ba-f0d22f669e86.png">

Hello  @janpauldahlke I'm not sure I understand the question could you please rephrase it.

**Comment by opeolluwa** [comment]
Do you mean to ask if there is a roadmap for the project?

**Comment by janpauldahlke** [comment]
yes. iam was giving the tipp as rust beginner to look around for repos to contribute to in open source. i can not use rust on work, so. atm iam into webservers, and found this interesting. so rephrasing: are there any tickets you need to geet done for further relases? kind regards

**Comment by opeolluwa** [comment]
@janpauldahlke that's for the clarification.  Could you please see the issues page regards this?  

I'd be happy to walk you thru where required

**Comment by janpauldahlke** [comment]
i will have a look around over the course of the wknd. :waves:

**Comment by opeolluwa** [comment]
I'll appreciate that. I'll also work on a roadmap
